### ISSUE TITLE
in_array (Line 49)

### ISSUE THREAD

**Issue by theWebKeyGuy** [Poruno/Bulma-Navwalker#2]
I keep getting this error on line 49 of the navwalker....

navwalker.php on line 49
Warning
: in_array() expects parameter 2 to be array, string given in

**Comment by benjaminmills15** [comment]
Following. Can't seem to figure this one out

**Comment by samuelbaute** [comment]
What worked for me is to be very cautious with the menu name. I mean:

`require_once('navwalker.php');`
`register_nav_menus( array(`
`    'primary' => __( 'Primary Menu', 'menuname' ), // This name has to be the same that the one here *1`
`) );`

`wp_nav_menu( array(`
`        'theme_location'    => 'primary', // *1`
`        'depth'             => 2,`
`        'container'         => false,`
`        // 'items_wrap'        => 'div',`
`        'menu_class'        => 'navbar-menu',`
`        'menu_id'           => 'primary-menu',`
`        'after'             => "</div>",`
`        'walker'            => new Navwalker())`
`);`

I was getting that error because I had registered the menu in other line with a different name.

**Comment by lewatt23** [comment]
Having the same problem .....  Any solution ?

**Comment by shahalpk** [comment]
FIxed the issue. Check https://github.com/shahalpk/Bulma-Navwalker

**Comment by jensendesign** [comment]
I changed the theme_location and it is working better, still need to do some adjustments but the error was gone.
```
wp_nav_menu( array(
        'theme_location'    => 'primary',
        'depth'             => 2,
        ...

<- changed to ->

wp_nav_menu( array(
        'theme_location'    => 'menu-1',
        'depth'             => 2,
        ...

**Comment by mysticbounce** [comment]
> FIxed the issue. Check https://github.com/shahalpk/Bulma-Navwalker

Can I pull request not be made for this fix?

**Comment by Ripecatfood** [comment]
Finally got back to programming. I've successfully reproduced the problem and have come up with a solution, which is by updating the readme as I've skipped a step last time I did this. Doing the first step should fix the problem. Update me otherwise.
