### ISSUE TITLE
How can I use this and still preserve WordPress classes from wp_nav_menu()

### ISSUE THREAD

**Issue by mware** [Poruno/Bulma-Navwalker#4]
Thanks for creating this. It does everything I need with one big exception. The [default WordPress menu classes](https://developer.wordpress.org/reference/functions/wp_nav_menu/) that would be assigned to active parents or children are missing.

How can I add them back? 
Namely:
`.current-menu-item`
`.current-menu-parent`

Thanks.

**Comment by Ripecatfood** [comment]
Hi! 
I didn't add it because vanilla Bulma.io **does not have a style** for **.current-menu-item** or **.current-menu-parent**. 
But if you add these 2 lines 
`if (in_array( 'current-menu-item', $item->classes, true )) { $liClasses .= " current-menu-item";  }`
`if (in_array( 'current-menu-parent', $item->classes, true )){ $liClasses .= " current-menu-parent"; }`
below line 31 it should produce the results you're looking for.


![screen](https://user-images.githubusercontent.com/14240204/120089560-b609ff00-c0c9-11eb-8b03-79dd13af21b8.png)

Sample with Custom Style:
`<style>`
`.current-menu-item,`
`.current-menu-item > .navbar-link  {`
`    box-shadow: inset 0 0 0 2px rgb(235, 255, 252) !important;`
`    color: rgb(0, 148, 126) !important;`
`}`
`.current-menu-parent > .navbar-link {`
`    box-shadow: inset 0 0 0 2px rgb(255,160,122) !important;`
`    color:  	rgb(255,160,122) !important;`
`}`
`</style>`

![home](https://user-images.githubusercontent.com/14240204/120089900-7c86c300-c0cc-11eb-9d68-4059b665d262.png)
![sample_page](https://user-images.githubusercontent.com/14240204/120089902-7ee91d00-c0cc-11eb-9289-4b1fd8dfe4da.png)
![custom_page](https://user-images.githubusercontent.com/14240204/120089903-80b2e080-c0cc-11eb-9b36-e4a923beae19.png)
![underpage](https://user-images.githubusercontent.com/14240204/120089904-81e40d80-c0cc-11eb-8256-288d953d6b39.png)

**Comment by mware** [comment]
Thank  you @Poruno. Worked perfectly!!
Michael
